#ifndef PQC_ENUMS_HPP
#define PQC_ENUMS_HPP

enum pqc_cipher {
	PQC_CIPHER_UNKNOWN = 0,
	PQC_CIPHER_CHACHA20,
	PQC_CIPHER_PLAIN,

	PQC_CIPHER_FIRST = PQC_CIPHER_CHACHA20,
	PQC_CIPHER_LAST = PQC_CIPHER_PLAIN
};

enum pqc_auth {
	PQC_AUTH_UNKNOWN = 0,
	PQC_AUTH_SIDHex_SHA512,

	PQC_AUTH_FIRST = PQC_AUTH_SIDHex_SHA512,
	PQC_AUTH_LAST = PQC_AUTH_SIDHex_SHA512
};

enum pqc_kex {
	PQC_KEX_UNKNOWN = 0,
	PQC_KEX_SIDHex,

	PQC_KEX_FIRST = PQC_KEX_SIDHex,
	PQC_KEX_LAST = PQC_KEX_SIDHex
};

enum pqc_mac {
	PQC_MAC_UNKNOWN = 0,
	PQC_MAC_HMAC_SHA256,
	PQC_MAC_HMAC_SHA512,

	PQC_MAC_FIRST = PQC_MAC_HMAC_SHA256,
	PQC_MAC_LAST = PQC_MAC_HMAC_SHA512
};

#endif /* PQC_ENUMS_HPP */
